# -*- coding: utf-8 -*-
"""Bone_XRay_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBnYOm9tElezoKnP6IbupiUvazr96xNE
"""

from google.colab import files
files.upload()

!pip install -q kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle --version

!ls

!kaggle datasets download -d anishakumari180404/bone-x-ray-disease-image-dataset --force

!unzip -o bone-x-ray-disease-image-dataset.zip

import os
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam

base_path = "bone_xray_dataset"
print(os.listdir(base_path))

datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2,
    rotation_range=10,
    zoom_range=0.1,
    horizontal_flip=True
)

train_data = datagen.flow_from_directory(
    base_path,
    target_size=(224,224),
    batch_size=8,
    class_mode="categorical",
    subset="training"
)

val_data = datagen.flow_from_directory(
    base_path,
    target_size=(224,224),
    batch_size=8,
    class_mode="categorical",
    subset="validation"
)

base_model = VGG16(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

# Freeze VGG16 layers
for layer in base_model.layers:
    layer.trainable = False

x = Flatten()(base_model.output)
x = Dense(256, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(train_data.num_classes, activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=15
)

model.save("bone_xray_vgg16_model.h5")

test_loss, test_acc = model.evaluate(val_data)
print("VGG16 Test Accuracy:", test_acc)

from tensorflow.keras.preprocessing import image
import random

classes = list(train_data.class_indices.keys())

actual_class = random.choice(os.listdir(base_path))
img_name = random.choice(os.listdir(os.path.join(base_path, actual_class)))
img_path = os.path.join(base_path, actual_class, img_name)

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)
img_array = preprocess_input(img_array)
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)
predicted_class = classes[np.argmax(prediction)]
confidence = np.max(prediction) * 100

plt.imshow(img)
plt.axis("off")

print("Actual:", actual_class)
print("Predicted:", predicted_class)
print(f"Confidence: {confidence:.2f}%")